### ISSUE TITLE
tearDown is not called if the test throws an exception

### ISSUE THREAD

**Issue by tylersnavely-wf** [dart-lang/unittest#35]
In the event an exception is thrown in a test, most test frameworks will catch the exception, fail the test, run tearDown, then rethrow the exception.

Is there any reason that this would be a bad idea?

**Comment by nex3** [comment]
This works for me on both `stable` and `master`.

```dart
// test.dart 
import "package:unittest/unittest.dart";

void main() {
  tearDown(() => print("in tearDown"));
  test("test", () => throw 'oh no');
}
```

On `stable`:

```shell
$ dart test.dart
unittest-suite-wait-for-done
in tearDown
ERROR: test
  Test failed: Caught oh no
  test.dart 5:22                                       main.<fn>
  package:unittest/src/internal_test_case.dart 120:37  run.<fn>
  dart:async/zone.dart 902                             _rootRunUnary
  dart:async/zone.dart 804                             _CustomZone.runUnary
  dart:async/future_impl.dart 484                      _Future._propagateToListeners.handleValueCallback
  dart:async/future_impl.dart 567                      _Future._propagateToListeners
  dart:async/future_impl.dart 358                      _Future._completeWithValue
  dart:async/future_impl.dart 412                      _Future._asyncComplete.<fn>
  dart:async/zone.dart 895                             _rootRun
  dart:async/zone.dart 796                             _CustomZone.run
  dart:async/zone.dart 704                             _CustomZone.runGuarded
  dart:async/zone.dart 729                             _CustomZone.bindCallback.<fn>
  dart:async/schedule_microtask.dart 41                _asyncRunCallbackLoop
  dart:async/schedule_microtask.dart 48                _asyncRunCallback
  dart:isolate-patch/isolate_patch.dart 96             _runPendingImmediateCallback
  dart:isolate-patch/isolate_patch.dart 143            _RawReceivePortImpl._handleMessage

0 PASSED, 0 FAILED, 1 ERRORS
Unhandled exception:
Exception: Some tests failed.
#0      SimpleConfiguration.onDone (package:unittest/src/simple_configuration.dart:197:9)
#1      _completeTests (package:unittest/unittest.dart:370:16)
#2      _runTest (package:unittest/unittest.dart:310:19)
#3      _nextTestCase (package:unittest/unittest.dart:258:11)
#4      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#5      _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#6      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:143)
```

On `master`:

```shell
$ dart test.dart
00:00 +0 -1: test
  oh no
  test.dart 5:22  main.<fn>
  
in tearDown
00:00 +0 -1: Some tests failed.
```
